---
# Rename file to app.yml to get started for development or test

production:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret
  MSG_KEY: <`rake generate:msg_key`>

development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret
  MSG_KEY: <`rake generate:msg_key`>

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret
  MSG_KEY: <`rake generate:msg_key`>