---
# Rename file to app.yml to get started for development or test

production:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret
  MSG_KEY: <`rake generate:msg_key`>
  REDISCLOUD_URL: <provision Redis instance>

development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret
  MSG_KEY: <`rake generate:msg_key`>
  REDISCLOUD_URL: redis://localhost:6379/

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret
  MSG_KEY: <`rake generate:msg_key`>
  REDISCLOUD_URL: redis://localhost:6379/