---
# Rename file to app.yml to get started for development or test

production:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret
  MSG_KEY: <`rake generate:msg_key`>
  SIGNING_KEY: <provision on API side through rake command>
  REDISCLOUD_URL: <provision Redis instance>
  GITHUB_OAUTH_SCOPE: user:email
  GITHUB_OAUTH_CLIENT_ID: <your_github_oauth_client_id>

development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret
  MSG_KEY: <`rake generate:msg_key`>
  SIGNING_KEY: 3U2+C5g+1oI8ijYr8EFv3NGd7doN7f9KbXM2G8ftmxE=
  REDISCLOUD_URL: redis://localhost:6379/
  GITHUB_OAUTH_SCOPE: user:email
  GITHUB_OAUTH_CLIENT_ID: <your_github_oauth_client_id>

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret
  MSG_KEY: <`rake generate:msg_key`>
  SIGNING_KEY: 3U2+C5g+1oI8ijYr8EFv3NGd7doN7f9KbXM2G8ftmxE=
  REDISCLOUD_URL: redis://localhost:6379/
  GITHUB_OAUTH_SCOPE: user:email
  GITHUB_OAUTH_CLIENT_ID: <your_github_oauth_client_id>